# Dev Stage 
FROM node:22-alpine AS dev

WORKDIR /projects/questify/frontend

COPY package*.json ./

#Define a build-time variable (build time => before npm install, runtime after the build process. prepare script is executed during npm install, hence build time variable setup is required.)
ARG VITE_PRODUCTION_ENVIRONMENT=false
ENV VITE_PRODUCTION_ENVIRONMENT=${VITE_PRODUCTION_ENVIRONMENT}

RUN npm ci

COPY . .

EXPOSE 5173

CMD [ "npm","run","dev" ]

